package com.google.android.gms.c;

import android.content.Context;
import com.google.android.gms.ads.internal.v;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

@pa
public final class is {
    public static final io<Long> A = io.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final io<Boolean> B = io.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final io<Long> C = io.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final io<Boolean> D = io.a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final io<Integer> E = io.a(1, "gads:video:spinner:scale", 4);
    public static final io<Long> F = io.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final io<Boolean> G = io.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final io<Boolean> H = io.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final io<String> I = io.b(0, "gads:spam_ad_id_decorator:experiment_id");
    public static final io<Boolean> J = io.a(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
    public static final io<Boolean> K = io.a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    public static final io<Float> L = io.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    public static final io<String> M = io.a(0, "gads:ad_id_app_context:experiment_id");
    public static final io<String> N = io.b(0, "gads:looper_for_gms_client:experiment_id");
    public static final io<Boolean> O = io.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final io<Boolean> P = io.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final io<Boolean> Q = io.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    public static final io<String> R = io.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final io<String> S = io.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final io<String> T = io.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final io<Boolean> U = io.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final io<String> V = io.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final io<Boolean> W = io.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final io<Boolean> X = io.a(1, "gads:use_adx_javascript_adapter", Boolean.valueOf(false));
    public static final io<Boolean> Y = io.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final io<Integer> Z = io.a(0, "gads:content_length_weight", 1);
    public static final io<String> a = io.a(0, "gads:sdk_core_experiment_id");
    public static final io<String> aA = io.b(0, "gads:pan:experiment_id");
    public static final io<String> aB = io.a(1, "gads:rewarded:experiment_id");
    public static final io<Long> aC = io.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final io<Boolean> aD = io.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final io<Long> aE = io.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final io<Long> aF = io.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final io<Boolean> aG = io.a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    public static final io<String> aH = io.a(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
    public static final io<Boolean> aI = io.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    public static final io<Long> aJ = io.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final io<Boolean> aK = io.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final io<Boolean> aL = io.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final io<String> aM = io.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final io<String> aN = io.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final io<Integer> aO = io.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final io<Integer> aP = io.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final io<Integer> aQ = io.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final io<String> aR = io.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final io<String> aS = io.a(1, "gads:spherical_video:vertex_shader", "");
    public static final io<String> aT = io.a(1, "gads:spherical_video:fragment_shader", "");
    public static final io<String> aU = io.a(1, "gads:spherical_video:experiment_id");
    public static final io<Boolean> aV = io.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final io<Boolean> aW = io.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final io<String> aX = io.a(1, "gads:include_local_global_rectangles:experiment_id");
    public static final io<Long> aY = io.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final io<Boolean> aZ = io.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final io<Integer> aa = io.a(0, "gads:content_age_weight", 1);
    public static final io<Integer> ab = io.a(0, "gads:min_content_len", 11);
    public static final io<Integer> ac = io.a(0, "gads:fingerprint_number", 10);
    public static final io<Integer> ad = io.a(0, "gads:sleep_sec", 10);
    public static final io<Boolean> ae = io.a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    public static final io<Integer> af = io.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final io<Boolean> ag = io.a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final io<Integer> ah = io.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final io<Integer> ai = io.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final io<String> aj = io.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final io<String> ak = io.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final io<Boolean> al = io.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final io<Boolean> am = io.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final io<Long> an = io.a(0, "gads:app_index:timeout_ms", 1000);
    public static final io<String> ao = io.a(0, "gads:app_index:experiment_id");
    public static final io<String> ap = io.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final io<Boolean> aq = io.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final io<Boolean> ar = io.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final io<Boolean> as = io.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final io<String> at = io.a(0, "gads:interstitial_follow_url:experiment_id");
    public static final io<Boolean> au = io.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    public static final io<Boolean> av = io.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final io<Integer> aw = io.a(0, "gads:webview_cache_version", 0);
    public static final io<Boolean> ax = io.a(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
    public static final io<String> ay = io.a(1, "gads:webview_recycle:experiment_id");
    public static final io<Boolean> az = io.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final io<String> b = io.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final io<Boolean> bA = io.a(1, "gads:gestures:touchinfo:enabled", Boolean.valueOf(false));
    public static final io<String> bB = io.a(1, "gads:gestures:touchinfo:experiment_id");
    public static final io<Boolean> bC = io.a(1, "gads:gestures:clock_query:enabled", Boolean.valueOf(false));
    public static final io<String> bD = io.a(1, "gads:gestures:clock_query:experiment_id");
    public static final io<Boolean> bE = io.a(1, "gads:gestures:clock_click:enabled", Boolean.valueOf(false));
    public static final io<String> bF = io.a(1, "gads:gestures:clock_click:experiment_id");
    public static io<Boolean> bG = io.a(1, "gads:gestures:btl_click:enabled", Boolean.valueOf(false));
    public static io<String> bH = io.a(1, "gads:gestures:btl_click:experiment_id");
    public static final io<String> bI = io.a(1, "gads:gestures:click_stk:experiment_id");
    public static final io<Boolean> bJ = io.a(1, "gads:gestures:click_stk:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bK = io.a(1, "gads:gestures:visibility:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bL = io.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bM = io.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bN = io.a(0, "gass:client:enabled", Boolean.valueOf(true));
    public static final io<String> bO = io.a(0, "gass:client:experiment_id");
    public static final io<Boolean> bP = io.a(0, "gass:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bQ = io.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final io<Boolean> bR = io.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bS = io.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bT = io.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final io<Boolean> bU = io.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final io<String> bV = io.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    public static final io<String> bW = io.a(1, "gads:sdk_core_constants:experiment_id");
    public static final io<String> bX = io.a(1, "gads:sdk_core_constants:caps", "");
    public static final io<Long> bY = io.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final io<Boolean> bZ = io.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final io<Long> ba = io.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final io<Boolean> bb = io.a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bc = io.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final io<Boolean> bd = io.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    public static final io<Boolean> be = io.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bf = io.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bg = io.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bh = io.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final io<Boolean> bi = io.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final io<String> bj = io.a(0, "gads:gmsg:video_meta:experiment_id");
    public static final io<Long> bk = io.a(0, "gads:network:cache_prediction_duration_s", 300);
    public static final io<Boolean> bl = io.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final io<Boolean> bm = io.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final io<Long> bn = io.a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final io<Long> bo = io.a(0, "gads:rendering:timeout_ms", 60000);
    public static final io<Boolean> bp = io.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final io<Long> bq = io.a(1, "gads:gestures:task_timeout", 2000);
    public static final io<String> br = io.a(1, "gads:gestures:encrypt_size_limit:experiment_id");
    public static final io<Boolean> bs = io.a(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
    public static final io<String> bt = io.a(1, "gads:gestures:appid:experiment_id");
    public static final io<Boolean> bu = io.a(1, "gads:gestures:appid:enabled", Boolean.valueOf(false));
    public static final io<Boolean> bv = io.a(0, "gads:gestures:v6:enabled", Boolean.valueOf(false));
    public static final io<String> bw = io.a(1, "gads:gestures:usb_query:experiment_id");
    public static final io<Boolean> bx = io.a(1, "gads:gestures:usb_query:enabled", Boolean.valueOf(false));
    public static final io<String> by = io.a(1, "gads:gestures:usb_click:experiment_id");
    public static final io<Boolean> bz = io.a(1, "gads:gestures:usb_click:enabled", Boolean.valueOf(false));
    public static final io<Boolean> c = io.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    public static final io<String> cA = io.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final io<Long> cB = io.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final io<String> cC = io.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
    public static final io<String> cD = io.a(0, "gads:afs:csa:experiment_id");
    public static final io<String> cE = io.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final io<String> cF = io.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final io<String> cG = io.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final io<String> cH = io.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final io<String> cI = io.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final io<Long> cJ = io.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final io<Boolean> cK = io.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    public static final io<Boolean> cL = io.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    public static final io<Boolean> cM = io.a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    public static final io<Long> cN = io.a(1, "gads:parental_controls:timeout", 2000);
    public static final io<String> cO = io.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    public static final io<Long> cP = io.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    public static final io<Boolean> cQ = io.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final io<Boolean> cR = io.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final io<Integer> cS = io.a(1, "gads:cache:max_concurrent_downloads", 10);
    public static final io<Long> cT = io.a(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final io<Boolean> cU = io.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final io<Boolean> cV = io.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final io<Boolean> cW = io.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final io<Long> cX = io.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final io<Boolean> cY = io.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final io<Boolean> cZ = io.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final io<Boolean> ca = io.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final io<String> cb = io.a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final io<String> cc = io.a(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final io<Boolean> cd = io.a(1, "gads:singleton_webview_native", Boolean.valueOf(false));
    public static final io<String> ce = io.a(1, "gads:singleton_webview_native:experiment_id");
    public static final io<Boolean> cf = io.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final io<Boolean> cg = io.a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final io<Boolean> ch = io.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final io<Integer> ci = io.a(1, "gads:native_video_load_timeout", 10);
    public static final io<String> cj = io.a(1, "gads:native_video_load_timeout:experiment_id");
    public static final io<String> ck = io.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final io<Boolean> cl = io.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final io<Boolean> cm = io.a(1, "gads:enable_tracking_for_native_ad_views", Boolean.valueOf(true));
    public static final io<Boolean> cn = io.a(1, "gads:use_new_json_for_native_view_tracking", Boolean.valueOf(true));
    public static final io<Boolean> co = io.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final io<Boolean> cp = io.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final io<Long> cq = io.a(0, "gads:method_tracing:duration_ms", 30000);
    public static final io<Integer> cr = io.a(0, "gads:method_tracing:count", 5);
    public static final io<Integer> cs = io.a(0, "gads:method_tracing:filesize", 134217728);
    public static final io<Boolean> ct = io.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    public static final io<String> cu = io.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final io<Long> cv = io.a(1, "gads:auto_location_timeout", 2000);
    public static final io<String> cw = io.b(1, "gads:auto_location_timeout:experiment_id");
    public static final io<Long> cx = io.a(1, "gads:auto_location_interval", -1);
    public static final io<String> cy = io.b(1, "gads:auto_location_interval:experiment_id");
    public static final io<Boolean> cz = io.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final io<String> d = io.a(0, "gads:request_builder:singleton_webview_experiment_id");
    public static final io<Boolean> da = io.a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(false));
    public static final io<Boolean> db = io.a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(false));
    public static final io<String> dc = io.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final io<String> dd = io.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final io<String> de = io.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final io<String> df = io.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final io<Integer> dg = io.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final io<Integer> dh = io.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final io<Boolean> di = io.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final io<Boolean> dj = io.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final io<Boolean> e = io.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    public static final io<String> f = io.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final io<Boolean> g = io.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final io<Boolean> h = io.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final io<String> i = io.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final io<Boolean> j = io.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    public static final io<String> k = io.a(0, "gads:block_autoclicks_experiment_id");
    public static final io<String> l = io.b(0, "gads:prefetch:experiment_id");
    public static final io<String> m = io.a(0, "gads:spam_app_context:experiment_id");
    public static final io<Boolean> n = io.a(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
    public static final io<Integer> o = io.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final io<String> p = io.a(1, "gads:video_exo_player:version", "1");
    public static final io<String> q = io.a(0, "gads:video_stream_cache:experiment_id");
    public static final io<Integer> r = io.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final io<Integer> s = io.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final io<Integer> t = io.a(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final io<Integer> u = io.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final io<Long> v = io.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final io<Long> w = io.a(1, "gads:video_stream_cache:notify_interval_millis", 1000);
    public static final io<Integer> x = io.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final io<Boolean> y = io.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final io<String> z = io.a(1, "gads:video:metric_frame_hash_times", "");

    public static List<String> a() {
        return v.p().a();
    }

    public static void a(final Context context) {
        sw.a(new Callable<Void>() {
            /* renamed from: a */
            public Void call() {
                v.q().a(context);
                return null;
            }
        });
    }

    public static List<String> b() {
        return v.p().b();
    }
}
