package com.google.android.gms.c;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.c;
import com.google.android.gms.common.api.c.a;
import com.google.android.gms.common.api.f;
import com.google.android.gms.common.api.g;

public class af<R extends f> extends c<R> {
    private final Status a;

    @Nullable
    public Integer a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void a(@NonNull a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void a(@NonNull g<? super R> gVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* Access modifiers changed, original: 0000 */
    @NonNull
    public Status b() {
        return this.a;
    }
}
